runtime: nodejs18 # or another supported version

instance_class: F2

handlers:

- url: /(.*\.(ico|png|json|svg))$
  static_files: \1
  upload: .*\.(ico|png|json|svg)$

- url: /static
  static_dir: static

- url: /api/.*
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  static_files: index.html
  upload: index.html

